# antidote setup
source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
antidote load

# taken from https://unix.stackexchange.com/questions/621606/zsh-completion-with-up-and-down-arrows#672892
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

eval "$(zoxide init zsh)"

# BEGIN opam configuration
# This is useful if you're using opam as it adds:
#   - the correct directories to the PATH
#   - auto-completion for the opam binary
# This section can be safely removed at any time if needed.
[[ ! -r "$HOME/.opam/opam-init/init.zsh" ]] || source "$HOME/.opam/opam-init/init.zsh" > /dev/null 2> /dev/null
# END opam configuration

export PATH="$PATH:$HOME/.cargo/bin/:$HOME/.rustup/toolchains/stable-aarch64-apple-darwin/bin/"
export EDITOR="nvim"

# highlight on tab selection
zstyle ':completion:*' menu select

# enable shift-tab to go backwards
bindkey '^[[Z' reverse-menu-complete

# disable colors in the output of some command
alias decolorize='sed "s/\x1B\[[0-9;]\{1,\}[A-Za-z]//g"'

# put uv tools on path
export PATH="$HOME/.local/bin:$PATH"

# add node to path
export PATH="/opt/homebrew/opt/node@24/bin:$PATH"

# add ghcup binaries to path
export PATH="$HOME/.ghcup/bin:$PATH"

# use forward slash as word separator
autoload -Uz select-word-style
select-word-style bash

# color ls output
alias ls='ls -G'

# enable starship prompt
eval "$(starship init zsh)"
